version: '3.9'

services:

  db:
    image: mysql:8.0.31
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # network_mode: "host"
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: bloodyroots
      # MYSQL_USER: groot
      # MYSQL_PASSWORD: stormbreaker
      # MYSQL_DATABASE: blog
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
