services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      # User: postgres
      POSTGRES_PASSWORD: bloodyroots
    volumes:
      - pgdata:/var/lib/postgresql/data
    # This is how you enable pg_stat_statements via Docker
    command: postgres -c shared_preload_libraries=pg_stat_statements

volumes:
  pgdata:
